travis:
  secure:
    BINSTAR_TOKEN: axCLj2OP6Xz2ljK636NgV+gfHWafSel7x3EHr1uUcRDn9UoISI0YuuQ2A302WpuTozKh9aKC90K6aLso4Ujmwc2B8mI/7uojDRt38/NdNxl5pDZ3tPbFXacwt9PNXNKzJqzU8PvRDo+JYadufFGUUXR3oADkh7a3gElXnzBgKED2b64X3CPTTAo1oBHIeWZUawgMi/5PC9PiN6xw3p1kPaUBhFb5C+Q1AlaJss30HCv2yPriTj0XTLW4AC8iMnXQzdQDuEu92/+pXVkiPpbZR9GServihGzfL/0up2pBfWlkQhJmoArPCoVXUQ31H7OJjyqa9dXlcqGZamnuwmYAI0ho0HdOsvjahIy2/iHOqohLowC9eU/5BMY5+kRt6G0zRHdBmMaaWkW2ywC/46sjyWwt7MlAdW286NSSIkrP/SI66erz0LawQaKg8hmkDTUiUKg7b7Jl0cChkZqtnY4sr00WCtrngAnliZrMJfYMUr7rss/XKsoy5G+r4bmprJE2n5dnH+Tp9DUfa2ei+BmboSXW/sK+6CYQDc9WHsGp06zGK73+NDceEdTsrUBJJcBEL0Iaw8Vy8EMDVILT9SQkMPWfF0kZBOhvI7MJldbH6yY6kMWF/bbroE8CRQFhMc7QRbeC09HYoqJEWHQNJJfcVSTsBFdOeAi7yGU6sko70O0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
